CONTIKI_PROJECT = etimer-buzzer rtimer-lightSensor rtimer-IMUSensor
all: $(CONTIKI_PROJECT)

TARGET = cc26x0-cc13x0
BOARD = sensortag/cc2650

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
CFLAGS += -w
